SqliteDemo/SqliteDemo/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SqliteDemo.Models.Entity;
using SqliteDemo.Models.Transaction;
using SqliteDemo.Models.Repository;

namespace SqliteDemo.Controllers
{
    public class AdminController : Controller
    {
        public ActionResult Index()
        {
            bool result = RepositoryManager.Repository.Initialize();
            return View();
        }

        /*
         * Handle a request for a listing of doctors.
         */
        public ActionResult List()
        {
            Doctor[] doctors = DoctorManager.GetAllDoctors();
            return View(doctors);
        }

        [HttpGet]
        public ActionResult DeleteDoctor()
        {
            return View(new Doctor());
        }
        [HttpPost]
        public ActionResult DeleteDoctor(Doctor delDoctor)
        {
            if (delDoctor.DoctorID == null || delDoctor.DoctorID.Length == 0)
            {
                ViewBag.message = "Error: An ID is required";
                return View(delDoctor);
            }
            bool result = DoctorManager.DeleteDoctor(delDoctor);
            if (result == false)
            {
                ViewBag.message = "Error: ID is wrong";
                return View(delDoctor);
            }
            ViewBag.message = "Doctor deleted";
            Doctor[] doctors = DoctorManager.GetAllDoctors();
            return View("List", doctors);
        }

        [HttpGet]
        public ActionResult ChangeDoctor()
        {
            return View(new Doctor());
        }
        [HttpPost]
        public ActionResult ChangeDoctor(Doctor changeDoctor)
        {
            bool result = DoctorManager.ChangeDoctor(changeDoctor);
            if (result == false)
            {
                ViewBag.message = "Error: Doctor not found";
                return View(changeDoctor);
            }
            ViewBag.message = "Doctor changed";
            Doctor[] doctors = DoctorManager.GetAllDoctors();
            return View("List", doctors);
        }
    }
}

SqliteDemo/SqliteDemo/Controllers/DoctorController.cs
using System.Web;
using System.Web.Mvc;
using SqliteDemo.Models.Entity;
using SqliteDemo.Models.Transaction;
using SqliteDemo.Models.Repository;

namespace SqliteTest.Controllers
{
    /*
     * This Controller handles requests related to Doctors.
     */
    public class DoctorController : Controller
    {
        public ActionResult Index()
        {
            bool result = RepositoryManager.Repository.Initialize();
            return View();
        }

        /*
         * Handle a request for a listing of doctors.
         */
        public ActionResult List()
        {
            Doctor[] doctors = DoctorManager.GetAllDoctors();
            return View(doctors);
        }

        /*
		 * Handle a GET request for the Add Doctor form.
         */
        [HttpGet]
        public ActionResult AddDoctor()
        {
            return View(new Doctor());
        }

        /*
         * Handle the POST request from the Add Doctor form. The form parameters
         * are encapsulated in a Doctor object.
         */
        [HttpPost]
        public ActionResult AddDoctor(Doctor newDoctor)
        {
            // Validate doctor data from the transaction
            if (newDoctor == null)
            {
                ViewBag.message = "Error: Invalid Request - please try again";
                return View(new Doctor());
            }
            if (newDoctor.DoctorID == null || newDoctor.DoctorID.Length == 0)
            {
                ViewBag.message = "Error: ID is required";
                return View(newDoctor);
            }
            if (newDoctor.Password == null || newDoctor.Password.Length == 0)
            {
                ViewBag.message = "Error: Name is required";
                return View(newDoctor);
            }

            // Add the doctor
            bool result = DoctorManager.AddNewDoctor(newDoctor);
            if (result)
            {
                ViewBag.message = "Doctor is added";
            }
            else
            {
                ViewBag.message = "That doctor could not be added";
            }

            Doctor[] doctors = DoctorManager.GetAllDoctors();
            return View("List", doctors);
        }

        [HttpGet]
        public ActionResult DeleteDoctor()
        {
            return View(new Doctor());
        }
        [HttpPost]
        public ActionResult DeleteDoctor(Doctor delDoctor)
        {
            if (delDoctor.DoctorID == null || delDoctor.DoctorID.Length == 0)
            {
                ViewBag.message = "Error: An ID is required";
                return View(delDoctor);
            }
            bool result = DoctorManager.DeleteDoctor(delDoctor);
            if (result == false)
            {
                ViewBag.message = "Error: ID is wrong";
                return View(delDoctor);
            }
            ViewBag.message = "Doctor deleted";
            Doctor[] doctors = DoctorManager.GetAllDoctors();
            return View("List", doctors);
        }

        [HttpGet]
        public ActionResult ChangeDoctor()
        {
            return View(new Doctor());
        }
        [HttpPost]
        public ActionResult ChangeDoctor(Doctor changeDoctor)
        {
            bool result = DoctorManager.ChangeDoctor(changeDoctor);
            if (result == false)
            {
                ViewBag.message = "Error: Doctor not found";
                return View(changeDoctor);
            }
            ViewBag.message = "Doctor changed";
            Doctor[] doctors = DoctorManager.GetAllDoctors();
            return View("List", doctors);
        }
    }
}

SqliteDemo/SqliteDemo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Physio Mate Web</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body style="background-color:white">
    <div class="navbar navbar-inverse navbar-fixed-top" style="background-color:#82d2dd">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Physio Mate", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse" style="color:black; font-size:larger">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Register", "AddDoctor", "Doctor")</li>
                    <li>@Html.ActionLink("Login", "Index", "Login")</li>
                    <li>@Html.ActionLink("Profile", "Admin", "LoggedIn")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <p style="background:white; padding:.5ex">@ViewBag.message</p>
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

    
</body>
</html>